blank_issues_enabled: true
contact_links:
  - name: Feature Requests / Suggestion
    url: https://github.com/understrap/understrap-roadmap/issues
    about: Please submit it to our public roadmap repository.
